version: '3'
services:
  django:
    container_name: django
    build:
      context: ./django
      dockerfile: Dockerfile.dev
    image: django:dev
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    depends_on:
      - db
    environment:
      - POSTGRES_DB=app-database
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-user-pass
      - DJANGO_SECRET_KEY=abcd
      - DJANGO_DEBUG=True


  db:
    container_name: db
    image: postgres:16.2
    environment:
      - POSTGRES_DB=app-database
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-user-pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
