# Generated by Django 5.0.3 on 2024-03-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_id', models.CharField(max_length=100, unique=True)),
                ('guests_max_number', models.PositiveIntegerField()),
                ('bathrooms_quantity', models.PositiveIntegerField()),
                ('accepts_animals', models.BooleanField(default=False)),
                ('cleaning_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activation_date', models.DateField()),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creation_timestamp'],
            },
        ),
    ]
