# Generated by Django 5.0.3 on 2024-03-10 18:32
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'initial_data.json', app_label='api')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
